### ISSUE TITLE
COI Calculator doesn't count extra production

### ISSUE THREAD

**Issue by serjevski** [doubleaxe/daxfb-calculator#10]
For example https://doubleaxe.github.io/daxfb-calculator/?link=ep9nk2o&name=captain-of-industry-new-blueprint 
We have extra yellow parts, bit it does not displayed at "output" pane. And assembly electric II r who assembles these parts does not accept full flows of incoming parts. Likewise, all other surpluses are not processed or counted. Especially in oil processing

**Comment by serjevski** [comment]
Oh, I saw the solution in one of the closed problems - a warehouse in passthru mode :)

**Comment by serjevski** [comment]
Oh.. my English is poor, maybe we can speak our natural language? :)))

**Comment by doubleaxe** [comment]
Здравствуйте. Да, если вам так удобнее :) Но вы же уже нашли ответ на свой вопрос.

Если есть предложения - пишите, но проект пока на паузе, я продолжу когда смогу заставить себя вернуться к нему.
