### ISSUE TITLE
Suggested feature: Upgrade/downgrade buildings

### ISSUE THREAD

**Issue by alsimoneau** [doubleaxe/daxfb-calculator#3]
I love your tool, it's really useful for planning COI production chains.

I would love it if there was a way to up/downgrade buildings in-place instead of having to remove it, change it for the new one, select the recipe and reconnect everything.  It would make upgrading production chains a lot simpler and help when deciding which tier of building (especially assemblies) is sufficient.

Cheers!

**Comment by doubleaxe** [comment]
Thanks for feedback, it means a lot that this tool is useful.

I planned this feature, but it is pretty hard to implement internally, and I was lazy. Ok, I will add it to my task list and implement it sooner or later.

**Comment by doubleaxe** [comment]
implemented in v1.0.17
