### ISSUE TITLE
Suggested feature: Storage output

### ISSUE THREAD

**Issue by alsimoneau** [doubleaxe/daxfb-calculator#7]
Storage having an output would allow to compute total resource draw on unbalanced systems. This can currently be done for systems with an overall production, but not for ones with an overall draw.

Moreover, with a toggle to force them to be balanced, they could be used to consolidate multiple in to multiple out systems, like an oil refinery with multiple sources of steam.

**Comment by doubleaxe** [comment]
The storages already have 3 modes of operation: input, output and passthrough. Passthrough mode will balance system and also show its output on 'Totals' page, other two will hide it. Also passthrough mode is useful if you wish to draw nicer line from producer to consumer. Mode is selected with recipe:

![image](https://github.com/doubleaxe/daxfb-calculator/assets/11171575/d9b55b94-2db0-4e55-ba2b-8f63f49e97af)

I'm not sure how should work force-balance mode for storages, actually you can limit and fine-tune storage output by entering non-integer numbers manually.

![image](https://github.com/doubleaxe/daxfb-calculator/assets/11171575/dc4fe9e6-1b40-4baa-ba8b-c61ac1d20ce0)

**Comment by alsimoneau** [comment]
I had missed that. Thanks.
